### ISSUE TITLE
Request for compilation instructions

### ISSUE THREAD

**Issue by kovan** [AppImage/appimaged#4] opened 2018-05-16 16:25 UTC
¿Can we have a compilation readme for this? I can't get it to compile

**Comment by probonopd** [comment] 2018-05-16 17:31
Thanks for pointing this out. It _used_ to work like documented [here](https://github.com/AppImage/AppImageKit/blob/appimagetool/master/README.md#building) but we are currently in the middle of moving this piece of code to this new repository. I assume @TheAssassin will add the compile information to the documentation soon.

**Comment by TheAssassin** [comment] 2018-05-16 17:34
@kovan you should provide at least some information on what you tried.

In a nutshell:

```
<install dependencies>
git clone https://github.com/AppImage/appimaged/
cd appimaged/
mkdir build/
cd build/
cmake ..
make
```

**Comment by TheAssassin** [comment] 2018-05-16 19:03
@kovan the _compiler_ doesn't find it? Are you sure you don't mean CMake?

This doesn't have anything to do with the extraction of this tool. The build system hasn't really changed.

You're just not providing enough information. Please add a full log of what you tried. Also you need to tell us what distro you're using at the moment...

**Comment by TheAssassin** [comment] 2018-05-16 19:27
@kovan who do you think put up this repository? I am building this just fine every time I develop on it. It works perfectly fine on Ubuntu 14.04, Ubuntu 16.04, and virtually any distro I tried.

If you refuse to provide additional information (like your distro, the most _basic_ kind of information for debugging), I think we have to close this issue as "cannot reproduce".

**Comment by kovan** [comment] 2018-05-16 19:57
Check my previous comment, I put all the info there.

**Comment by TheAssassin** [comment] 2018-05-16 21:29
@kovan ah, that makes sense. You need to fetch the Git submodules with `git submodule update --init`. Then, it should work. I edited my above comment to include the `--recursive` flag in the clone call which provides the same functionality.

But this is not at all a compiler message. Nor it's complaining about a missing glib header. This is a CMake error.

**Comment by kovan** [comment] 2018-05-16 21:52
OK now yes, it compiles. Probably you should put those instructions in the readme.

**Closed as completed** 2018-05-16 22:22 UTC
