### ISSUE TITLE
unreel-1.3.0-x86_64.AppImage is crashing the appimaged process

### ISSUE THREAD

**Issue by freddii** [AppImage/appimaged#58] opened 2019-01-25 16:11 UTC
I placed unreel-1.3.0-x86_64.AppImage in a folder appimaged scans.
/home/$USER/.local/bin/

Then appimaged crashed with:
free(): invalid pointer
Aborted (core dumped)

https://github.com/linux-man/unreel/releases/download/v1.3.0/unreel-1.3.0-x86_64.AppImage

The new AppImage 1.4.0 of unreel works.
So the bug got somehow fixed between 1.3.0 and 1.4.0.
https://github.com/linux-man/unreel/releases/download/v1.4.0/unreel-1.4.0-x86_64.AppImage

**Comment by probonopd** [comment] 2019-01-25 16:46
I can reproduce this on `xubuntu-18.04-desktop-amd64.iso`. 

```
_________________________

(appimaged:12466): GLib-CRITICAL **: 17:42:30.472: g_file_test: assertion 'filename != NULL' failed
free(): invalid pointer
Aborted
me@host:~$ appimaged --version
appimaged, continuous build (commit 660c916), build 65 built on 2018-12-06 18:38:08 UTC
```

Interestingly, the [experimental build that is using libappimage 0.2](https://artifacts.assassinate-you.net/artifactory/appimaged/travis-87/appimaged-x86_64.AppImage) does not suffer from this:

```
me@host:~$ appimaged --version
appimaged, continuous build (commit 3b794f3), build 86 built on 2019-01-18 04:35:47 UTC
```

**Comment by freddii** [comment] 2019-01-25 23:05
This appimaged version is not crashing.
 A desktop entry for unreel is not added.
Maybe a desktop entry is not possible, cause unreels Desktop file is malformed. like @azubieta said.
$ ./appimaged-x86_64.AppImage -n
appimaged, continuous build (commit c0332c8), build 87 built on 2019-01-22 06:58:18 UTC

https://artifacts.assassinate-you.net/artifactory/appimaged/travis-87/appimaged-x86_64.AppImage

**Comment by brunoleon** [comment] 2019-02-25 19:23
digikam-6.0.0-x86-64
kdenlive-18.12.1-x86_64

also crash appimaged
```

AppImage type 2
AppImage type 2

(appimaged:8874): GLib-CRITICAL **: 20:21:34.471: g_file_test: assertion 'filename != NULL' failed
AppImage type 2
zsh: segmentation fault (core dumped)  /usr/bin/appimaged -v
```

**Comment by probonopd** [comment] 2019-02-26 06:17
@TheAssassin @azubieta we need to switch this to libappimage 0.2 soon since that version resolves this issue.

**Comment by probonopd** [comment] 2019-02-26 21:01
To everyone who is affected, please try the latest continuous build, it should be fixed now. If so, it would be nice if you could confirm. Thank you very much.

**Comment by freddii** [comment] 2019-02-27 01:14
the latest continious build from https://github.com/AppImage/appimaged/releases is not working for me.

$ ./appimaged-x86_64.AppImage -v
appimaged, continuous build (commit 86c09a7), build 96 built on 2019-02-26 16:37:28 UTC

I tryed it with:
https://github.com/X0rg/CPU-X/releases/download/v3.2.4/CPU-X_v3.2.4_x86_64.AppImage

if i put the appimage in ~/Applications it adding the appimage correctly.
But if i remove the appimage, the starter does not get removed.


But this is working with appimaged from:
https://artifacts.assassinate-you.net/artifactory/appimaged/travis-87/appimaged-x86_64.AppImage
$ ./appimaged-x86_64.AppImage -n
appimaged, continuous build (commit c0332c8), build 87 built on 2019-01-22 06:58:18 UTC

**Comment by probonopd** [comment] 2019-02-27 05:35
Please check @azubieta, thanks.

**Comment by azubieta** [comment] 2019-02-27 17:40
@freddii @probonopd that seems to be another totally different issue. Probably related to the random behavior of `inotify`. If you agreed I would like to close this and open a new issue.

**Comment by probonopd** [comment] 2019-02-27 17:50
Yes, let's open a new issue for it @azubieta

**Comment by azubieta** [comment] 2019-02-27 21:36
Closed, discussion about the new issue will be continued at #69

**Closed by azubieta** 2019-02-27 21:36 UTC
