### ISSUE TITLE
Get rid of git submodules if they cannot be managed by the GitHub web interface

### ISSUE THREAD

**Issue by probonopd** [AppImage/appimaged#80] opened 2019-05-05 14:35 UTC
Get rid of git submodules if they cannot be managed by the GitHub web interface.

Currently we have

![submodule](https://user-images.githubusercontent.com/2480569/57195480-b06d7980-6f42-11e9-87a9-2b60c7528964.png)

I have no clue how to 
1. Update it using the GitHub IDE (without resorting to using a local git client)
2. Make sure _always the latest_ is used without having to do manual updating each time `libappimage` changes
3. Trigger an automated rebuild of this repository if `libappimage` changes (including pull requests in libappimage, so that one can get AppImages that contain the total net result of change in `libappimage`)

Regarding 1., why not have the `.travis.yml` script to do

```
  - ( cd appimaged/lib/ ; git clone -o 86c4cca https://github.com/AppImage/libappimage )
```

instead (if we want to fix it to a certain commit)?

Regarding 2., 

```
  - ( cd appimaged/lib/ ; git clone https://github.com/AppImage/libappimage )
```

if we always want to have the _latest_ (which I prefer)?

Regarding 3., I have no clue how to do that short of using a [monorepo](https://github.com/AppImage/AppImageKit/issues/931).

**Comment by probonopd** [comment] 2019-05-05 14:39
Current example: I need an `appimaged` with https://github.com/AppImage/libappimage/pull/108.

**Comment by probonopd** [comment] 2019-05-05 14:40
Or is there a better way to do this @TheAssassin?

**Comment by probonopd** [comment] 2019-05-05 15:20
To update on currently has to use local tools and do a rather involved sequence:

```
git clone --recursive https://github.com/AppImage/appimaged
cd appimaged/lib/libappimage/
git checkout master
git pull
cd ..
git add libappimage/
git commit -m "Update libappimage"
git push
```

**Comment by shoogle** [comment] 2019-05-06 20:27
Presumably you already have the `appimaged` repo on your machine, in which case you can skip the cloning step and just update the submodule.

If you want to always build against the latest `libappimage` just add this to `.travis.yml`:

```bash
( cd appimaged/lib/ ; git checkout master )
```

The disadvantage is that Travis is building against a different version of `libappimage` to the one that contributors have installed on their machines. If the build fails due to problems in the latest `libappimage` then contributors will wonder why the build succeeded on their own machine.

**Comment by TheAssassin** [comment] 2019-05-07 21:44
A suggestion that leads only to problems. But hey, I don't really care after all. Just a bit sad that this kind of inconsistency made it into the build scripts. Just leads to weirdnesses.

**Comment by probonopd** [comment] 2019-05-07 21:53
Can we remove git submodules from this repository entirely, so that _everyone_ gets the _latest_ automatically? How?

**Comment by TheAssassin** [comment] 2019-05-07 22:05
Do I really have to explain why this is a bad idea?

People use IDEs. People like IDEs. The sources must be there, in the right locations, and shall be manageable through the IDEs.
People also like to clone repositories and have all the sources.
People _also_ like reproducibility of builds. Reproducible builds are only possible when you fix the versions of things a specific commit builds against.
... the list could be continued waaaay more than that.

**Comment by probonopd** [comment] 2019-05-07 22:07
Define "people". Looks like `appimaged` is mainly cared for by me. And my IDE is the GitHub web interface...

**Comment by TheAssassin** [comment] 2019-05-07 23:25
You were asking about "everyone". I would say a vast majority uses local development environments.

The inconsistencies and issues with reproducibility are independent from that.

**Comment by shoogle** [comment] 2019-05-08 01:42
You can always add a check to see which commit `libappimage` is currently at, which it is at after the submodule update, and if they are different then you print a big warning message. Something like:

*WARNING: This build is using version c8c53e4 of libappimage, which is more recent than version ea24d5b currently checked into the repository. If errors occur that you cannot reproduce on your local machine, try updating your local copy of libappimage.*

You can also overload the `after_failure` build step:

```yml
after_failure:
  - [[ "${VERSION1}" != "${VERSION2}" ]] && echo "Try updating the libappimage submodule to the latest upstream version."
```

You could even do something really fancy in the `after_failure` step, like try the whole build again using the older version.

Alternatively you could use a build matrix to always build against both versions of the library. Simply do the submodule update in one build job and not the other.

**Comment by shoogle** [comment] 2019-05-08 01:45
BTW I make a mistake in my code before (and you should have tested locally before committing). It should have been `cd lib/libappimage` not `cd appimaged/lib`. I updated my [comment](https://github.com/AppImage/appimaged/issues/80#issuecomment-489764083). You might also need to do `git pull` or `git fetch origin` before you do `git checkout master`.

**Comment by probonopd** [comment] 2019-05-08 06:18
@TheAssassin 

>  I would say a vast majority uses local development environments.

The majority of `appimaged` developers?

@shoogle the warnings just mean that now it tells me that I need to do more manual work. I want to get rid of manual work. I want everything fully automated. Every code change shall produce updated binaries of everything. No manual work involved... (this is my hobby and I don't like repetitive manual work)

**Comment by shoogle** [comment] 2019-05-08 10:54
@probonopd, the warning are not for you, they are for other contributors. In any case, you can have the message appear only if the build fails. In that situation it is not giving extra work, merely reminding you (or informing others) of a possible cause of a problem which would need to be fixed anyway.

**Closed** 2019-05-11 07:43 UTC
