### ISSUE TITLE
GitHubDesktop-linux-1.6.0-linux1.AppImage is crashing the appimaged process

### ISSUE THREAD

**Issue by freddii** [AppImage/appimaged#56] opened 2019-01-25 09:47 UTC
I placed GitHubDesktop-linux-1.6.0-linux1.AppImage in a folder appimaged scans. 
/home/$USER/.local/bin/

Then appimaged crashed with:
munmap_chunk(): invalid pointer
Aborted (core dumped)

So do not place it in common folders for appimaged. 
But run it once, then it will create its own working starter.

https://github.com/shiftkey/desktop/releases/download/release-1.6.0-linux1/GitHubDesktop-linux-1.6.0-linux1.AppImage

**Comment by TheAssassin** [comment] 2019-01-25 12:37
@azubieta mind to have a look? `mmap` etc. aren't used in appimaged's code base, but in libappimage they're used occassionally, so this is probably a bug in libappimage.

**Comment by freddii** [comment] 2019-01-25 17:33
works with that experimental build.

./appimaged-x86_64.AppImage --version
appimaged, continuous build (commit c0332c8), build 87 built on 2019-01-22 06:58:18 UTC

**Comment by azubieta** [comment] 2019-01-25 18:14
@freddii I'm not being able to reproduce this error. Would you mind to mention the name of the system you are using, it's version and architecture. Also, please the appimaged version as you did above.
Thanks

**Comment by freddii** [comment] 2019-01-25 22:50
This appimaged version works without crashing:
$ ./appimaged-x86_64.AppImage -n
appimaged, continuous build (commit c0332c8), build 87 built on 2019-01-22 06:58:18 UTC

https://artifacts.assassinate-you.net/artifactory/appimaged/travis-87/appimaged-x86_64.AppImage


The latest version from github did not work for any Appimage.
No desktop files are created. But it does not crash.
$ ./appimaged-x86_64_github.AppImage -n
appimaged, continuous build (commit 1dd440a), build 88 built on 2019-01-25 18:18:24 UTC

https://github.com/AppImage/appimaged/releases/download/continuous/appimaged-x86_64.AppImage


I am using Xubuntu 18.04 Bionic 64 bit.

**Comment by probonopd** [comment] 2019-02-03 18:05
Likely a duplicate of #58, since closing here

**Closed by probonopd** 2019-02-03 18:05 UTC
